version: 2

aliases:
  - &restore_cache
    keys:
      - v1-yarn-lock-{{ checksum "yarn.lock" }}
  - &save_cache
    paths:
      - ~/.cache/yarn
    key: v1-yarn-lock-{{ checksum "yarn.lock" }}
  - &filter_master
    branches:
      only: master

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:10.9.0-browsers

jobs:
  all_in_one:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: yarn --frozen-lockfile
      - run: yarn run build
      - run: yarn run test
      - save_cache: *save_cache

workflows:
  version: 2
  build-all:
    jobs:
      - all_in_one
